[project]
name = "agentic-ai-for-safety-monitoring-with-construction-risk-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Harveen Kaur", email = "harveenkaur282@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
agentic-ai-for-safety-monitoring-with-construction-risk-analytics = "agentic_ai_for_safety_monitoring_with_construction_risk_analytics:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
